### ISSUE TITLE
After trying to send an invitation to new user an internal server error is thrown

### ISSUE THREAD

**Issue by mmuller** [instedd/act#34]
Go to the list of  Users
Press 'New User'
Fill the form
Press 'Send invitation'

Obtained: internal server error is thrown

**Comment by matiasgarciaisaia** [comment]
We just need to configure the e-mail account for the app to send the invitations

**Comment by matiasgarciaisaia** [comment]
It's still happening in production - raising priority.

**Comment by pmallol** [comment]
Ok in staging
