### ISSUE TITLE
The client breakes after enlarging or maximising it

### ISSUE THREAD

**Issue by pmallol** [instedd/act#65]
Found in client version 1.0.4

1. Open the ACT Client
2. Enlarge or maximize the Client

Obtained: the buttons located next to options 'Show all' and 'Only unread' move down to the middle section between the options and the patient's table.

Expected: the buttons should remain next to the options and move as a block

![screen shot 2015-01-16 at 12 34 02 pm](https://cloud.githubusercontent.com/assets/9214460/5778719/2902da72-9d7c-11e4-9dd6-2626e7bcbdc6.png)

**Comment by matiasgarciaisaia** [comment]
Preliminary version for testing before it gets included in a new release: https://www.dropbox.com/s/a8pm7au5ffd96hn/ACT-win32-dev-5c9a076.exe?dl=1
