### ISSUE TITLE
Apply style based on Brand to Web app

### ISSUE THREAD

**Issue by nditada** [instedd/act#66]

**Comment by matiasgarciaisaia** [comment]
Fixed with:
b7aafe4eb7f8479e5e9d78d247ca313739339d87
5d22f0c3a956e3379a840ce92801a601ac3ac0b3
4aab52b3720bb5ac3fb045c9bff98241d5800d59
b6f9aafbad16b182888a32b985c42932f61dc808
c544e08eb84356584d9f6be8d9926bea2b12c031
df19c5bc0ff8221d463eb1f426eff468632e0136
dcc95467ac0cfdcbd2ab3fd028743acd62eb4476
